---
# tasks file for /home/david/Documents/altschool/projects/final-project/php8.1

 
  - name: Installation install software-properties-common
    apt: name=software-properties-common

  # - name: "Repo PHP 8.1"
  #   apt_repository:
  #     repo="ppa:ondrej/php"

  - name: "Updating the repo"
    apt: update_cache=yes

  # - name: Install php8.1 directly
  #   shell: |
  #     sudo apt install --no-install-recommends php8.1


  - name: Installation PHP 8.1
    apt: name=php8.1 state=present

  - name: install lamp stack
    apt:
      pkg:
        - php8.1-mysql
        - php8.1-curl
        # - php8.1-json
        - php8.1-cgi
        - php8.1-xsl
        - php8.1-cgi
        - php8.1-gd
        - php8.1-mbstring
        - php8.1-zip
        - php8.1-xmlrpc
        - php8.1-soap
        - php8.1-intl
        - libapache2-mod-php
      state: present
      update_cache: yes
