---
# tasks file for composer

    - name: Check if Compose exits
      stat: path=/usr/local/bin/composer
      register: fileStat


    - name: Install Compose
      shell: |
        curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
        sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      when: not fileStat.stat.exists


